name: Deploy to cPanel

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy .htaccess to dist
        run: cp public/.htaccess dist/.htaccess

      - name: List build files (debug)
        run: ls -la dist/

      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to cPanel via FTP
        env:
          FTP_HOST: ${{ secrets.CPANEL_HOST }}
          FTP_USER: ${{ secrets.CPANEL_USERNAME }}
          FTP_PASS: ${{ secrets.CPANEL_PASSWORD }}
          FTP_PORT: ${{ secrets.CPANEL_PORT }}
          FTP_DIR: ${{ secrets.CPANEL_REMOTE_PATH }}
        run: |
          lftp -c "
          set ftp:ssl-allow no;
          open -u $FTP_USER,$FTP_PASS -p $FTP_PORT $FTP_HOST;
          cd $FTP_DIR || exit 1;
          lcd dist;
          mirror --reverse --delete --verbose --exclude-glob=.git* --exclude-glob=node_modules/*;
          quit
          "

