name: Deploy to cPanel

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy .htaccess to dist
        run: cp public/.htaccess dist/.htaccess

      - name: List build files (debug)
        run: ls -la dist/

      - name: Install FTP client
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Debug - List FTP directory structure
        env:
          FTP_HOST: ${{ secrets.CPANEL_HOST }}
          FTP_USER: ${{ secrets.CPANEL_USERNAME }}
          FTP_PASS: ${{ secrets.CPANEL_PASSWORD }}
          FTP_PORT: ${{ secrets.CPANEL_PORT }}
        run: |
          echo "Listing FTP root directory..."
          lftp -c "
          set ftp:ssl-allow no;
          open -u $FTP_USER,$FTP_PASS -p $FTP_PORT $FTP_HOST;
          pwd;
          ls -la;
          quit
          "

      - name: Deploy to cPanel via FTP (Clean & Replace)
        env:
          FTP_HOST: ${{ secrets.CPANEL_HOST }}
          FTP_USER: ${{ secrets.CPANEL_USERNAME }}
          FTP_PASS: ${{ secrets.CPANEL_PASSWORD }}
          FTP_PORT: ${{ secrets.CPANEL_PORT }}
          FTP_DIR: ${{ secrets.CPANEL_REMOTE_PATH }}
        run: |
          lftp -c "
          set ftp:ssl-allow no;
          open -u $FTP_USER,$FTP_PASS -p $FTP_PORT $FTP_HOST;
          echo 'Current directory after login:';
          pwd;
          echo 'Attempting to change to: $FTP_DIR';
          cd $FTP_DIR || (
            echo 'Failed with absolute path. Trying relative path...';
            cd public_html || (
              echo 'Failed with public_html. Trying /public_html...';
              cd /public_html || (
                echo 'All path attempts failed. Current directory contents:';
                ls -la;
                exit 1
              )
            )
          );
          echo 'Successfully changed to:';
          pwd;
          echo 'Cleaning all existing WordPress files...';
          # Delete WordPress directories
          rm -rf wp-admin wp-content wp-includes || true;
          # Delete WordPress core files
          rm -f wp-*.php index.php license.txt readme.html wp-config-sample.php wp-load.php wp-blog-header.php wp-comments-post.php wp-cron.php wp-links-opml.php wp-activate.php || true;
          # Delete any other WordPress-related files
          rm -f error_log xmlrpc.php .htaccess || true;
          echo 'Deleted WordPress files. Starting upload of new React app...';
          lcd dist;
          # Use mirror with delete to sync files (uploads new, deletes any remaining old files)
          mirror --reverse --delete --verbose --exclude-glob=.git* --exclude-glob=node_modules/* --parallel=5;
          quit
          "

